# Generated by Django 5.2.5 on 2025-08-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pecas', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField(auto_now_add=True)),
                ('dataSaida', models.DateField(blank=True, null=True)),
                ('feito', models.BooleanField(default=False)),
                ('valorTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pecas', models.ManyToManyField(blank=True, related_name='ordens_servico', to='pecas.peca')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='servicos.servico')),
            ],
        ),
    ]
