# Generated by Django 5.2.5 on 2025-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServicos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='Kilometragem',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
