# Generated by Django 5.2.5 on 2025-10-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServicos', '0003_ordemservico_kilometragem'),
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas',
        ),
        migrations.CreateModel(
            name='PecaUsada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeUsada', models.PositiveIntegerField(default=1)),
                ('ordemServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemServicos.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pecas.peca')),
            ],
        ),
    ]
