# Generated by Django 5.2.5 on 2025-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServicos', '0004_remove_ordemservico_pecas_pecausada'),
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, related_name='ordens_servico', through='ordemServicos.PecaUsada', to='pecas.peca'),
        ),
    ]
